### PR TITLE
BlockCypher testnet parameters with unit tests

### PR DESCRIPTION
**Pull request by mflaxman**
This PR replaces @matthieu's previous one here:
https://github.com/sbuss/bitmerchant/pull/39

I forked it and added passing test vectors.

Thanks again @sbuss  for putting your library out there. I've been playing around with it and it's really well written!

### CODE REVIEW

**Comment by sbuss** [comment]
Thanks for the new test vectors! How did you generate them? The existing BIP32 text vectors were generated by using pycoin; did you alter the `generate_bip32_test_vectors.py` script to make it more general?

Also you've got a test failure. Looks like you missed a call to `test_file`. From travis-ci:

```
.E............................................................................................................
======================================================================
ERROR: test_file (tests.test_bip32_vector.TestBIP32)
----------------------------------------------------------------------
TypeError: test_file() takes exactly 3 arguments (1 given)
----------------------------------------------------------------------
Ran 110 tests in 392.001s
```

**Comment by mflaxman** [comment]
Oops, sorry about that @sbuss!

I wasn't using travis-ci to run the test and was calling it individually with different syntax.  The travis-ci build failed because `test_file()` was a helper method only called by `test_bip32_files()` but since the helper method starts with `test_` travis-ci was trying to call it. I added an underscore prefix and now the helper method is no longer mistakenly called and the tests seem to pass (at least in 2.6 and 3.3, still waiting on 2.7 to return a result but I suspect it will be done by the time you read this).

Re the test vectors, I did modify `generate_bip32_test_vectors.py` (nice use of argparse btw) to generate them, but I did it with bitmerchant so I didn't commit the script. I realize this is quite a hack (verifying the test vectors generated by the library itself!), but this was just to save @matthieu time. He then ran my test vectors against his golang codebase and they passed. So I guess this commit is now the official source for test vectors for blockcypher's testnet coin. Does that make sense?

Also, would you mind updating pypi once you approve this PR? I've just bumped the version number.

Thanks!

**Comment by mflaxman** [comment]
Hey @sbuss, all the Travis CI tests did in fact pass... Is there anything else you're waiting on to merge this PR? Thanks!

**Comment by sbuss** [comment]
>  He then ran my test vectors against his golang codebase and they passed. So I guess this commit is now the official source for test vectors for blockcypher's testnet coin.

Sounds good; glad you validated it.

I'm going to revert your update to the version number, since I like to do that specifically in a release branch. Granted, that release branch will just contain this PR, but I like to be consistent.

**Comment by sbuss** [comment]
> I'm going to revert your update to the version number

Actually, since this PR is from a fork I guess you need to do that. As soon as you revert fa6298c I'll merge in.

**Comment by mflaxman** [comment]
Makes sense. To keep the commit history clean I went back to the previous commit and created a new PR (instead of reverting):
https://github.com/sbuss/bitmerchant/pull/43

Does that work?

Thanks!

**Pull request closed without merging**
