### PR TITLE
BlockCypher testnet parameters with unit tests #2

### PR DESCRIPTION
**Pull request by mflaxman**
This PR is different from https://github.com/sbuss/bitmerchant/pull/40 in that per your request @sbuss it excludes the version change I made in https://github.com/mflaxman/bitmerchant/commit/fa6298ca04c0b72050073f70779ccdffe0afdd87

Thanks!

### CODE REVIEW

**Comment by sbuss** [comment]
Thanks for the new constants and tests, @mflaxman @matthieu 

Expect this to be up on pypi by the end of the week.

**Comment by mflaxman** [comment]
Thanks @sbuss!

**Comment by mflaxman** [comment]
Thanks for merging this @sbuss!

Are you planning to do a new pypi release soon? I'm writing some code that has bitmerchant as a dependency.

**Comment by sbuss** [comment]
@mflaxman I pushed a new release to pypi on Sunday. Cheers!

**Comment by mflaxman** [comment]
Thanks @sbuss !

**Pull request merged**
